name: "Prepare release"

on:
  workflow_dispatch:
    inputs:
      VERSION:
        type: string
        description: "Semantic Version (X.X.X)"
        required: true

jobs:
  prepare-release:
    name: "Prepare new release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare git config
        run: |
          git config user.name "Alexey Release-kun"
          git config user.email "noreply@github.com"

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dotnet-tools
        run: dotnet tool install -g dotnet-setversion

      - name: Checkout to release branch
        run: git checkout -b release/${{ github.event.inputs.VERSION }}

      - name: Upgrade projects version
        run: setversion --recursive ${{ github.event.inputs.VERSION }}

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@3.0.0
        with:
          tag: ${{ github.event.inputs.VERSION }}

      - name: Commit changelog and manifest files
        run: |
          git add CHANGELOG.md *.csproj
          git commit --message "Release ${{ github.event.inputs.VERSION }}"

          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push release branch
        run: git push origin release/${{ github.event.inputs.VERSION }}

      - name: Open pull request
        uses: thomaseizinger/create-pull-request@1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.VERSION }}
          base: main
          title: Release version ${{ github.event.inputs.VERSION }}
          body: |
            This PR was opened in response to a manual trigger of the release workflow.

            Merging this PR will create a GitHub release.

            by Alexey Release-kun
